name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-macos-arm:
    name: Build macOS ARM Application
    runs-on: macos-latest  # ARM64 (Apple Silicon)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      
      - name: Install dependencies
        run: |
          uv sync
          uv pip install pyinstaller==6.3.0
      
      - name: Build with PyInstaller
        run: |
          uv run pyinstaller gui_app.spec
      
      - name: Create ZIP archive with ditto
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent HRSLinkageTool.app HRSLinkageTool-macOS-ARM.zip
      
      - name: Upload macOS ARM build artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm-build
          path: dist/HRSLinkageTool-macOS-ARM.zip
          retention-days: 5

  build-windows:
    name: Build Windows Application
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      
      - name: Install dependencies
        run: |
          uv sync
          uv pip install pyinstaller==6.3.0
      
      - name: Build with PyInstaller
        run: |
          uv run pyinstaller gui_app.spec
      
      - name: Create ZIP archive
        run: |
          cd dist
          Compress-Archive -Path HRSLinkageTool -DestinationPath HRSLinkageTool-Windows.zip
        shell: pwsh
      
      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/HRSLinkageTool-Windows.zip
          retention-days: 5

  create-release:
    name: Create GitHub Release
    needs: [build-macos-arm, build-windows]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download macOS ARM build
        uses: actions/download-artifact@v4
        with:
          name: macos-arm-build
          path: ./artifacts
      
      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: ./artifacts
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./artifacts/HRSLinkageTool-macOS-ARM.zip
            ./artifacts/HRSLinkageTool-Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

